CREATE TABLE `uzivatel` (
    `uid` INT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(32) UNIQUE NOT NULL,
    `password_hash` VARCHAR(60) NOT NULL
);

CREATE TABLE `tag` (
   `tag_id` INT PRIMARY KEY AUTO_INCREMENT,
   `nazev` VARCHAR(32) NOT NULL UNIQUE,
   `popis` VARCHAR(255),
   `autor_tag` INT REFERENCES `uzivatel`(`uid`)
);

CREATE TABLE `balicek` (
    `balicek_id` INT PRIMARY KEY AUTO_INCREMENT,
    `nazev` VARCHAR(32) NOT NULL,
    `popis` TEXT,
    `autor_balicek` INT REFERENCES `uzivatel`(`uid`)
);

CREATE TABLE `tag_balicek` (
    `balicek_id` INT,
    `tag_id` INT,
    PRIMARY KEY (`balicek_id`, `tag_id`),
    FOREIGN KEY (`balicek_id`) REFERENCES `balicek`(`balicek_id`),
    FOREIGN KEY (`tag_id`) REFERENCES `tag`(`tag_id`)
);

CREATE TABLE `karty` (
    `name` VARCHAR(50) PRIMARY KEY,
    `id` VARCHAR(50) NOT NULL,
    `deck` VARCHAR(50) NOT NULL,
    `row` VARCHAR(50) NOT NULL,
    `strength` VARCHAR(50) NOT NULL,
    `ability` VARCHAR(50) NOT NULL,
    `filename` VARCHAR(50) NOT NULL,
    `count` VARCHAR(50) NOT NULL
);

CREATE TABLE `balik_karta` (
   `karta_name` VARCHAR(50) REFERENCES `karty`(`name`),
   `balicek_id` INT REFERENCES `balicek`(`balicek_id`),
   `pocet` INT NOT NULL,
   PRIMARY KEY (`karta_name`, `balicek_id`)
);

INSERT INTO `karty` (`name`, `id`, `deck`, `row`, `strength`, `ability`, `filename`, `count`)
VALUES
    ('Mysterious Elf', '142', 'neutral', 'close', '0', 'hero spy', 'mysterious_elf', '1'),
    ('Decoy', '1', 'special', '', '', 'decoy', 'decoy', '3'),
    ('Biting Frost', '4', 'weather', '', '', 'frost', 'frost', '3'),
    ('Cirilla Fiona Elen Riannon', '139', 'neutral', 'close', '15', 'hero muster', 'ciri', '1'),
    ('Clear Weather', '7', 'weather', '', '', 'clear', 'clear', '2'),
    ('Commander''s Horn', '2', 'special', '', '', 'horn', 'horn', '3'),
    ('Dandelion', '11', 'neutral', 'close', '2', 'horn', 'dandelion', '1'),
    ('Emiel Regis Rohellec Terzieff', '', 'neutral', 'close', '5', '', 'emiel', '1'),
    ('Geralt of Rivia', '138', 'neutral', 'close', '15', 'hero muster', 'geralt', '1'),
    ('Impenetrable Fog', '5', 'weather', '', '', 'fog', 'fog', '3'),
    ('Scorch', '3', 'special', '', '', 'scorch', 'scorch', '3'),
    ('Torrential Rain', '6', 'weather', '', '', 'rain', 'rain', '2'),
    ('Triss Merigold', '141', 'neutral', 'close', '7', 'hero', 'triss', '1'),
    ('Vesemir', '9', 'neutral', 'close', '6', '', 'vesemir', '1'),
    ('Villentretenmerth', '8', 'neutral', 'close', '7', 'scorch_c', 'villen', '1'),
    ('Yennefer of Vengerberg', '140', 'neutral', 'ranged', '7', 'hero medic', 'yennefer', '1'),
    ('Zoltan Chivay', '10', 'neutral', 'close', '5', '', 'zoltan', '1'),
    ('Olgierd von Everec', '', 'neutral', 'agile', '6', 'morale', 'olgierd', '1'),
    ('Gaunter O''Dimm', '', 'neutral', 'siege', '2', 'muster', 'gaunter_odimm', '1'),
    ('Gaunter O''Dimm - Darkness', '', 'neutral', 'ranged', '4', 'muster', 'gaunter_odimm_darkness', '3'),
    ('Cow', '', 'neutral', 'ranged', '0', 'avenger', 'cow', '1'),
    ('Bovine Defense Force', '', 'neutral', 'close', '8', '', 'chort', '0'),
    ('Foltest - King of Temeria', '5', 'realms', 'leader', '', 'foltest_king', 'foltest_silver', '1'),
    ('Foltest - Lord Commander of the North', '8', 'realms', 'leader', '', 'foltest_lord', 'foltest_gold', '1'),
    ('Foltest - The Siegemaster', '6', 'realms', 'leader', '', 'foltest_siegemaster', 'foltest_copper', '1'),
    ('Foltest - The Steel-Forged', '7', 'realms', 'leader', '', 'foltest_steelforged', 'foltest_bronze', '1'),
    ('Foltest - Son of Medell', '', 'realms', 'leader', '', 'foltest_son', 'foltest_son_of_medell', '1'),
    ('Ballista', '79', 'realms', 'siege', '6', '', 'ballista', '1'),
    ('Blue Stripes Commando', '92', 'realms', 'close', '4', 'bond', 'blue_stripes', '3'),
    ('Catapult', '75', 'realms', 'siege', '8', 'bond', 'catapult_1', '2'),
    ('Crinfrid Reavers Dragon Hunter', '87', 'realms', 'ranged', '5', 'bond', 'crinfrid', '3'),
    ('Dethmold', '76', 'realms', 'ranged', '6', '', 'dethmold', '1'),
    ('Dun Banner Medic', '88', 'realms', 'siege', '5', 'medic', 'banner_nurse', '1'),
    ('Esterad Thyssen', '11', 'realms', 'close', '10', 'hero', 'esterad', '1'),
    ('John Natalis', '10', 'realms', 'close', '10', 'hero', 'natalis', '1'),
    ('Kaedweni Siege Expert', '98', 'realms', 'siege', '1', 'morale', 'kaedwen_siege', '1'),
    ('Keira Metz', '84', 'realms', 'ranged', '5', '', 'keira', '1'),
    ('Philippa Eilhart', '12', 'realms', 'ranged', '10', 'hero', 'philippa', '1'),
    ('Poor Fucking Infantry', '95', 'realms', 'close', '1', 'bond', 'poor_infantry', '4'),
    ('Prince Stennis', '86', 'realms', 'close', '5', 'spy', 'stennis', '1'),
    ('Redanian Foot Soldier', '96', 'realms', 'close', '1', '', 'redania', '1'),
    ('Sheldon Skaggs', '91', 'realms', 'ranged', '4', '', 'sheldon', '1'),
    ('Siege Tower', '81', 'realms', 'siege', '6', '', 'siege_tower', '1'),
    ('Siegfried of Denesle', '83', 'realms', 'close', '5', '', 'siegfried', '1'),
    ('Sigismund Dijkstra', '89', 'realms', 'close', '4', 'spy', 'dijkstra', '1'),
    ('Síle de Tansarville', '85', 'realms', 'ranged', '5', '', 'sheala', '1'),
    ('Thaler', '94', 'realms', 'siege', '1', 'spy', 'thaler', '1'),
    ('Sabrina Glevissig', '90', 'realms', 'ranged', '4', '', 'sabrina', '1'),
    ('Vernon Roche', '9', 'realms', 'close', '10', 'hero', 'vernon', '1'),
    ('Ves', '82', 'realms', 'close', '5', '', 'ves', '1'),
    ('Yarpen Zigrin', '93', 'realms', 'close', '2', '', 'yarpen', '1'),
    ('Trebuchet', '77', 'realms', 'siege', '6', '', 'trebuchet', '1'),
    ('Emhyr var Emreis - His Imperial Majesty', '1', 'nilfgaard', 'leader', '', 'emhyr_imperial', 'emhyr_silver', '1'),
    ('Emhyr var Emreis - Emperor of Nilfgaard', '2', 'nilfgaard', 'leader', '', 'emhyr_emperor', 'emhyr_copper', '1'),
    ('Emhyr var Emreis - the White Flame', '3', 'nilfgaard', 'leader', '', 'emhyr_whiteflame', 'emhyr_bronze', '1'),
    ('Emhyr var Emreis - The Relentless', '4', 'nilfgaard', 'leader', '', 'emhyr_relentless', 'emhyr_gold', '1'),
    ('Emhyr var Emreis - Invader of the North', '', 'nilfgaard', 'leader', '', 'emhyr_invader', 'emhyr_invader_of_the_north', '1'),
    ('Albrich', '68', 'nilfgaard', 'ranged', '2', '', 'albrich', '1'),
    ('Assire var Anahid', '52', 'nilfgaard', 'ranged', '6', '', 'assire', '1'),
    ('Black Infantry Archer', '47', 'nilfgaard', 'ranged', '10', '', 'black_archer', '1'),
    ('Cahir Mawr Dyffryn aep Ceallach', '54', 'nilfgaard', 'close', '6', '', 'cahir', '1'),
    ('Cynthia', '60', 'nilfgaard', 'ranged', '4', '', 'cynthia', '1'),
    ('Etolian Auxiliary Archers', '72', 'nilfgaard', 'ranged', '1', 'medic', 'archer_support', '1'),
    ('Fringilla Vigo', '53', 'nilfgaard', 'ranged', '6', '', 'fringilla', '1'),
    ('Heavy Zerrikanian Fire Scorpion', '49', 'nilfgaard', 'siege', '10', '', 'heavy_zerri', '1'),
    ('Impera Brigade Guard', '67', 'nilfgaard', 'close', '3', 'bond', 'imperal_brigade', '4'),
    ('Letho of Gulet', '147', 'nilfgaard', 'close', '10', 'hero', 'letho', '1'),
    ('Menno Coehoorn', '148', 'nilfgaard', 'close', '10', 'hero medic', 'menno', '1'),
    ('Morteisen', '64', 'nilfgaard', 'close', '3', '', 'morteisen', '1'),
    ('Morvran Voorhis', '149', 'nilfgaard', 'siege', '10', 'hero', 'moorvran', '1'),
    ('Nausicaa Cavalry Rider', '71', 'nilfgaard', 'close', '2', 'bond', 'nauzicaa_2', '3'),
    ('Puttkammer', '66', 'nilfgaard', 'ranged', '3', '', 'puttkammer', '1'),
    ('Rainfarn', '61', 'nilfgaard', 'close', '4', '', 'rainfarn', '1'),
    ('Renuald aep Matsen', '56', 'nilfgaard', 'ranged', '5', '', 'renuald', '1'),
    ('Rotten Mangonel', '65', 'nilfgaard', 'siege', '3', '', 'rotten', '1'),
    ('Shilard Fitz-Oesterlen', '51', 'nilfgaard', 'close', '7', 'spy', 'shilard', '1'),
    ('Siege Engineer', '55', 'nilfgaard', 'siege', '6', '', 'siege_engineer', '1'),
    ('Siege Technician', '74', 'nilfgaard', 'siege', '0', 'medic', 'siege_support', '1'),
    ('Stefan Skellen', '50', 'nilfgaard', 'close', '9', 'spy', 'stefan', '1'),
    ('Sweers', '69', 'nilfgaard', 'ranged', '2', '', 'sweers', '1'),
    ('Tibor Eggebracht', '150', 'nilfgaard', 'ranged', '10', 'hero', 'tibor', '1'),
    ('Vanhemar', '62', 'nilfgaard', 'ranged', '4', '', 'vanhemar', '1'),
    ('Vattier de Rideaux', '63', 'nilfgaard', 'close', '4', 'spy', 'vattier', '1'),
    ('Vreemde', '70', 'nilfgaard', 'close', '2', '', 'vreemde', '1'),
    ('Young Emissary', '58', 'nilfgaard', 'close', '5', 'bond', 'young_emissary', '1'),
    ('Zerrikanian Fire Scorpion', '57', 'nilfgaard', 'siege', '5', '', 'zerri', '1'),
    ('Eredin - Commander of the Red Riders', '134', 'monsters', 'leader', '', 'eredin_commander', 'eredin_silver', '1'),
    ('Eredin - Bringer of Death', '136', 'monsters', 'leader', '', 'eredin_bringer_of_death', 'eredin_bronze', '1'),
    ('Eredin - Destroyer of Worlds', '137', 'monsters', 'leader', '', 'eredin_destroyer', 'eredin_gold', '1'),
    ('Eredin - King of the Wild Hunt', '135', 'monsters', 'leader', '', 'eredin_king', 'eredin_copper', '1'),
    ('Eredin Bréacc Glas - The Treacherous', '', 'monsters', 'leader', '', 'eredin_treacherous', 'eredin_the_treacherous', '1'),
    ('Arachas ', '27', 'monsters', 'close', '4', 'muster', 'arachas', '1'),
    ('Arachas- Behemoth', '15', 'monsters', 'siege', '6', 'muster', 'arachas_behemoth', '1'),
    ('Botchling', '26', 'monsters', 'close', '4', '', 'poroniec', '1'),
    ('Celaeno Harpy', '38', 'monsters', 'agile', '2', '', 'celaeno_harpy', '1'),
    ('Cockatrice', '36', 'monsters', 'ranged', '2', '', 'cockatrice', '1'),
    ('Crone - Brewess', '16', 'monsters', 'close', '6', 'muster', 'witch_velen', '1'),
    ('Crone - Weavess', '17', 'monsters', 'close', '6', 'muster', 'witch_velen_1', '1'),
    ('Crone - Whispess', '18', 'monsters', 'close', '6', 'muster', 'witch_velen_2', '1'),
    ('Draug', '143', 'monsters', 'close', '10', 'hero', 'draug', '1'),
    ('Earth Elemental', '12', 'monsters', 'siege', '6', '', 'earth_elemental', '1'),
    ('Endrega', '34', 'monsters', 'ranged', '2', '', 'endrega', '1'),
    ('Fiend', '13', 'monsters', 'close', '6', '', 'fiend', '1'),
    ('Fire Elemental', '14', 'monsters', 'siege', '6', '', 'fire_elemental', '1'),
    ('Foglet', '39', 'monsters', 'close', '2', '', 'fogling', '1'),
    ('Forktail', '19', 'monsters', 'close', '5', '', 'forktail', '1'),
    ('Frightener', '23', 'monsters', 'close', '5', '', 'frightener', '1'),
    ('Gargoyle', '37', 'monsters', 'ranged', '2', '', 'gargoyle', '1'),
    ('Ghoul', '44', 'monsters', 'close', '1', 'muster', 'ghoul', '1'),
    ('Grave Hag', '25', 'monsters', 'ranged', '5', '', 'gravehag', '1'),
    ('Griffin', '21', 'monsters', 'close', '5', '', 'gryffin', '1'),
    ('Harpy', '35', 'monsters', 'agile', '2', '', 'harpy', '1'),
    ('Ice Giant', '24', 'monsters', 'siege', '5', '', 'frost_giant', '1'),
    ('Imlerith', '144', 'monsters', 'close', '10', 'hero', 'imlerith', '1'),
    ('Kayran', '146', 'monsters', 'agile', '8', 'hero morale', 'kayran', '1'),
    ('Leshen', '145', 'monsters', 'ranged', '10', 'hero', 'leshen', '1'),
    ('Nekker', '41', 'monsters', 'close', '2', 'muster', 'nekker', '1'),
    ('Plague Maiden', '20', 'monsters', 'close', '5', '', 'mighty_maiden', '1'),
    ('Vampire - Bruxa', '33', 'monsters', 'close', '4', 'muster', 'bruxa', '1'),
    ('Vampire - Ekimmara', '30', 'monsters', 'close', '4', 'muster', 'ekkima', '1'),
    ('Vampire - Fleder', '31', 'monsters', 'close', '4', 'muster', 'fleder', '1'),
    ('Vampire - Garkain', '32', 'monsters', 'close', '4', 'muster', 'garkain', '1'),
    ('Vampire - Katakan', '', 'monsters', 'close', '5', 'muster', 'katakan', '1'),
    ('Werewolf', '22', 'monsters', 'close', '5', '', 'werewolf', '1'),
    ('Wyvern', '40', 'monsters', 'ranged', '2', '', 'wyvern', '1'),
    ('Toad', '', 'monsters', 'ranged', '7', 'scorch_r', 'toad', '1'),
    ('Francesca Findabair - Queen of Dol Blathanna', '13', 'scoiatael', 'leader', '', 'francesca_queen', 'francesca_silver', '1'),
    ('Francesca Findabair - the Beautiful', '14', 'scoiatael', 'leader', '', 'francesca_beautiful', 'francesca_gold', '1'),
    ('Francesca Findabair - Daisy of the Valley', '15', 'scoiatael', 'leader', '', 'francesca_daisy', 'francesca_copper', '1'),
    ('Francesca Findabair - Pureblood Elf', '16', 'scoiatael', 'leader', '', 'francesca_pureblood', 'francesca_bronze', '1'),
    ('Francesca Findabair - Hope of the Aen Seidhe', '', 'scoiatael', 'leader', '', 'francesca_hope', 'francesca_hope_of_the_aen_seidhe', '1'),
    ('Ciaran aep Easnillien', '122', 'scoiatael', 'agile', '3', '', 'ciaran', '1'),
    ('Barclay Els', '106', 'scoiatael', 'agile', '6', '', 'barclay', '1'),
    ('Dennis Cranmer', '102', 'scoiatael', 'close', '6', '', 'dennis', '1'),
    ('Dol Blathanna Archer', '121', 'scoiatael', 'ranged', '4', '', 'dol_archer', '1'),
    ('Dol Blathanna Scout', '107', 'scoiatael', 'agile', '6', '', 'dol_infantry', '1'),
    ('Dwarven Skirmisher', '123', 'scoiatael', 'close', '3', 'muster', 'dwarf', '1'),
    ('Eithné', '17', 'scoiatael', 'ranged', '10', 'hero', 'eithne', '1'),
    ('Elven Skirmisher', '127', 'scoiatael', 'ranged', '2', 'muster', 'elf_skirmisher', '1'),
    ('Filavandrel aen Fidhail', '104', 'scoiatael', 'agile', '6', '', 'filavandrel', '1'),
    ('Havekar Healer', '131', 'scoiatael', 'ranged', '0', 'medic', 'havekar_nurse', '1'),
    ('Havekar Smuggler', '110', 'scoiatael', 'close', '5', 'muster', 'havekar_support', '1'),
    ('Ida Emean aep Sivney', '103', 'scoiatael', 'ranged', '6', '', 'ida', '1'),
    ('Iorveth', '20', 'scoiatael', 'ranged', '10', 'hero', 'iorveth', '1'),
    ('Isengrim Faoiltiarna', '19', 'scoiatael', 'close', '10', 'hero morale', 'isengrim', '1'),
    ('Mahakaman Defender', '115', 'scoiatael', 'close', '5', '', 'mahakam', '1'),
    ('Milva', '101', 'scoiatael', 'ranged', '10', 'morale', 'milva', '1'),
    ('Riordain', '130', 'scoiatael', 'ranged', '1', '', 'riordain', '1'),
    ('Saesenthessis', '18', 'scoiatael', 'ranged', '10', 'hero', 'saskia', '1'),
    ('Toruviel', '126', 'scoiatael', 'ranged', '2', '', 'toruviel', '1'),
    ('Vrihedd Brigade Recruit', '120', 'scoiatael', 'ranged', '4', '', 'vrihedd_cadet', '1'),
    ('Vrihedd Brigade Veteran', '113', 'scoiatael', 'agile', '5', '', 'vrihedd_brigade', '1'),
    ('Yaevinn', '105', 'scoiatael', 'agile', '6', '', 'yaevinn', '1'),
    ('Berserker', '', 'skellige', 'close', '4', 'berserker', 'berserker', '1'),
    ('Birna Bran', '', 'skellige', 'close', '2', 'medic', 'birna', '1'),
    ('Blueboy Lugos', '', 'skellige', 'close', '6', '', 'blueboy', '1'),
    ('Cerys', '', 'skellige', 'close', '10', 'hero muster', 'cerys', '1'),
    ('Clan Brokva Archer', '', 'skellige', 'ranged', '6', '', 'brokva_archer', '2'),
    ('Clan Dimun Pirate', '', 'skellige', 'ranged', '6', 'scorch', 'dimun_pirate', '1'),
    ('Cerys - Clan Drummond Shield Maiden', '', 'skellige', 'close', '4', 'bond', 'shield_maiden', '1'),
    ('Clan Heymaey Skald', '', 'skellige', 'close', '4', '', 'heymaey', '1'),
    ('Clan Tordarroch Armorsmith', '', 'skellige', 'close', '4', '', 'tordarroch', '1'),
    ('Clan an Craite Warrior', '', 'skellige', 'close', '6', 'bond', 'craite_warrior', '3'),
    ('Donar an Hindar', '', 'skellige', 'close', '4', '', 'donar', '1'),
    ('Draig Bon-Dhu', '', 'skellige', 'siege', '2', 'horn', 'draig', '1'),
    ('Ermion', '', 'skellige', 'ranged', '8', 'hero mardroeme', 'ermion', '1'),
    ('Hemdall', '', 'skellige', 'close', '11', 'hero', 'hemdall', '0'),
    ('Hjalmar', '', 'skellige', 'ranged', '10', 'hero', 'hjalmar', '1'),
    ('Holger Blackhand', '', 'skellige', 'siege', '4', '', 'holger', '1'),
    ('Kambi', '', 'skellige', 'close', '0', 'avenger_kambi', 'kambi', '1'),
    ('Light Longship', '', 'skellige', 'ranged', '4', 'muster', 'light_longship', '3'),
    ('Madman Lugos', '', 'skellige', 'close', '6', '', 'madmad_lugos', '1'),
    ('Mardroeme', '', 'special', '', '', 'mardroeme', 'mardroeme', '3'),
    ('Olaf', '', 'skellige', 'agile', '12', 'morale', 'olaf', '1'),
    ('Skellige Storm', '', 'weather', '', '', 'rain fog', 'storm', '3'),
    ('Svanrige', '', 'skellige', 'close', '4', '', 'svanrige', '1'),
    ('Transformed Vildkaarl', '', 'skellige', 'close', '14', 'morale', 'vildkaarl', '0'),
    ('Transformed Young Vildkaarl', '', 'skellige', 'ranged', '8', 'bond', 'young_vildkaarl', '0'),
    ('Udalryk', '', 'skellige', 'close', '4', '', 'udalryk', '1'),
    ('War Longship', '', 'skellige', 'siege', '6', 'bond', 'war_longship', '2'),
    ('Young Berserker', '', 'skellige', 'ranged', '2', 'berserker', 'young_berserker', '3'),
    ('Crach an Craite', '', 'skellige', 'leader', '', 'crach_an_craite', 'crach_an_craite', '0'),
    ('King Bran', '', 'skellige', 'leader', '', 'king_bran', 'king_bran', '0'),
    ('Schirru', '', 'scoiatael', 'siege', '8', 'scorch_s', 'schirru', '1'),
    ('Roach', '', 'neutral', 'close', '3', '', 'roach', '1');


