<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="resources/stylesheet.css">
    <title>Document</title>
</head>
<body>
    <div>
        <nav class="nav">
            <ul class="nav-list">
                <li><a href="">Home</a></li>
                <li><a href="">About</a></li>
                <li><a href="">Contact</a></li>
                <li><a href="">Account</a></li>
            </ul>
            
        </nav>
        <main class="main">
            <div class="left-panel">
                <h2>Left Panel</h2>
            </div>
            <div class="center-panel">
                <h1>Decks</h1>
            </div>
            <div class="right-panel">
                <h2>Right Panel</h2>
            </div>
        </main>
    </div>
</body>
</html>