<div class="login-container">
    <h1>Login</h1>
    <form method="post" class="login-form">
        <?php
            if (isset($loginOK)) {
                if (!$loginOK) {
                    echo "<p style='color: red;'>Přihlášení neúspěšné!</p>";
                }
            }
        ?>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <input type="submit">

        <a class="login-toreg" href="/register">Don't have an account? Register here.</a>
    </form>
</div>