<div class="login-container">
    <form method="post" class="login-form">
        <h1>Login</h1>
        <?php
            //print_r(get_defined_vars());
            if (isset($loginOK)) {
                if (!$loginOK) {
                    echo "<p style='color: red;'>Login not successful, check your password and try again.</p>";
                } else {
                    session_start();
                    var_dump($_SESSION);
                }
            }
        ?>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <input type="submit">

        <a class="login-toreg" href="/register">Don't have an account? Register here.</a>
    </form>
</div>