<div>
    <main class="main">
        <div class="left-panel">
            <h2>Left Panel</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            

        </div>
        <div class="center-panel">
            <h1>Decks</h1>
        </div>
        <div class="right-panel">
            <h2>Right Panel</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci dolore quaerat velit molestias odit pariatur sed dolorem unde quidem, sapiente, vero nihil nesciunt qui aliquam blanditiis natus hic expedita rerum.</p>
        </div>
    </main>
</div>