<div class="login-container">
    <form method="post" class="login-form">
        <h1>Register</h1>
        <?php
        if (isset($userExists)) {
            echo "<p style='color: red'>Uživatel již existuje!</p>";
        } else if (isset($otherError)) {
            echo "<p style='color: red'>Neznámá chyba, zkuste to znovu.</p>";
        }
        ?>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <input type="submit">
    </form>
</div>