<div class="login-container">
    <form method="post" class="login-form">
        <h1>Create an Account</h1>
        <?php
        if (isset($userExists)) {
            echo "<p style='color: red'>User with this username already exists!</p>";
        } else if (isset($otherError)) {
            echo "<p style='color: red'>Unknown error, please try again later.</p>";
        }
        ?>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <input type="submit" value="CREATE ACCOUNT">
    </form>
</div>