<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/pohledy/resources/stylesheet.css">
</head>
<body>
        <nav class="nav">
            <ul class="nav-list">
                <li><a href="/main">Home</a></li>
                <li><a href="/baliky">Decks</a></li>
                <li><a href="/about">About</a></li>
                <!-- Změnit jak se dostává na register -->
                <li><a href="/register">Account</a></li>
            </ul>
        </nav>
    <?php
    // PHP code goes here
        $this->kontroler->vypisPohled();
    ?>
</body>
</html>